#!/bin/sh

# This should be run from the root/workspace folder

ROOTDIR="$PWD"
WEBAPPDIR="$ROOTDIR"/src/webapp
CLASP="$ROOTDIR"/tools/node_modules/.bin/clasp

if [ ! -d "$WEBAPPDIR" ]; then
	echo "Unable to find webapp in $WEBAPPDIR" >&2
	exit 1
fi

if [ ! -x "$CLASP" ]; then
	echo "Unable to find clasp at $CLASP." >&2
	exit 1
fi

cd "$WEBAPPDIR" || {
	echo "Unable to enter directory '$WEBAPPDIR'" >&2
	exit 1
}

if [ "You are not logged in." = "$("$CLASP" login --status)" ]; then
	"$CLASP" login
fi

"$CLASP" push
