#!/bin/sh

GHIDRA="/usr/local/Caskroom/ghidra/9.2.2,20201229/ghidra_9.2.2_PUBLIC/support/analyzeHeadless"
GHIDRAPROJECTS="/Users/chjones/Development/Marvel Future Fight/ghidra"
IMPORTSCRIPT="/Users/chjones/Development/Marvel Future Fight/mffer/src/ImportC.py"
DEVICEFILEDIR="/Users/chjones/Development/Marvel Future Fight/device-files/MFF-device-6.9.0"

PROJECTNAME="mff-ghidra-6.9.0"
LIBIL2CPP="$(find "$DEVICEFILEDIR" -type f -name libil2cpp.so)"
GLOBALMETADATA="$(find "$DEVICEFILEDIR" -type f -name global-metadata.dat)"
SOURCEDIR="$(dirname "$LIBIL2CPP")"
DESTDIR="$GHIDRAPROJECTS/$PROJECTNAME"
if [ -d "$DESTDIR" ]; then
	echo "The project directory $DESTDIR already exists; will not overwrite." >&2
	echo "Remove $DESTDIR to attempt creating a new analysis project." >&2
	exit 1
fi

cleanup() {
	rm -rf "$MFFTEMPDIR"
	kill -- -$$
}

MFFTEMPDIR="$(mktemp -d)" || {
	echo 'Unable to create temporary directory. Exiting.' >&2
	exit 1
}
trap 'cleanup' EXIT HUP INT QUIT TERM

I2CIDIR="$MFFTEMPDIR/Il2CppInspector"
HEADERDIR="$I2CIDIR/Il2CppInspector.CLI/cpp/appdata"
BINDIR="$I2CIDIR/Il2CppInspector.CLI/bin/Release/netcoreapp3.1/osx-x64"
SCRIPTDIR="$I2CIDIR/Il2CppInspector.CLI"
cd "$MFFTEMPDIR" || {
	echo 'Unable to enter temporary directory. Exiting.' >&2
	exit 1
}
git clone --recursive -b 2021.1 https://github.com/djkaty/Il2CppInspector || {
	echo 'Unable to obtain Il2CppInspector. Exiting.' >&2
	exit 1
}
cd "$I2CIDIR/Il2CppInspector.CLI" || {
	echo 'Unable to enter Il2CppInspector directory. Exiting.' >&2
	exit 1
}
dotnet publish -r osx-x64 -c Release || {
	echo 'Unable to build Il2CppInspector. Exiting.' >&2
	exit 1
}

mkdir -p "$DESTDIR" "$BINDIR/plugins"
"$GHIDRA" "$DESTDIR" "$PROJECTNAME" -import "$SOURCEDIR/"* -noanalysis \
	-loader ElfLoader -loader-imagebase 0 \
	-log "$DESTDIR"/"$PROJECTNAME"-import.log

"$BINDIR"/Il2CppInspector -p il2cpp.py -t Ghidra \
	-i "$LIBIL2CPP" -m "$GLOBALMETADATA"

HEADERFILE="$HEADERDIR/il2cpp-types.h"
sed '/^typedef struct Il2CppString Il2CppString;$/s/$/'"\n"'typedef struct Il2CppStringBuilder Il2CppStringBuilder;/' \
	"$HEADERFILE" >"$HEADERFILE-new" && mv "$HEADERFILE-new" "$HEADERFILE"

cp "$IMPORTSCRIPT" "$SCRIPTDIR"

"$GHIDRA" "$DESTDIR" "$PROJECTNAME" -process "libil2cpp.so" -noanalysis \
	-scriptPath "$SCRIPTDIR" \
	-preScript "$(basename "$IMPORTSCRIPT")" "$HEADERFILE" -preScript il2cpp.py \
	-log "$DESTDIR"/"$PROJECTNAME"-il2cpp.log \
	-scriptlog "$DESTDIR"/"$PROJECTNAME"-scripts.log

"$GHIDRA" "$DESTDIR" "$PROJECTNAME" -process "libil2cpp.so" \
	-log "$DESTDIR"/"$PROJECTNAME"-analysis.log
