name: Build on macOS
on:
  workflow_dispatch:
  pull_request:
jobs:
  build-mffer:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build
